apiVersion: v1
kind: Namespace
metadata:
  name: silverfox-scrapers
  labels:
    app: silverfox-scraper-system
    environment: production
    version: v1.0.0
  annotations:
    description: "Silver Fox Marketing - Automotive Dealership Scraper System"
    contact: "Silver Fox Marketing Team"
    created-by: "Claude Code Assistant"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: silverfox-resource-quota
  namespace: silverfox-scrapers
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8" 
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "10"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: silverfox-limit-range
  namespace: silverfox-scrapers
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "200m"
      memory: "512Mi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim